name: linux-nightly-h100
on:
  workflow_call:
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN:
        required: True
        description: |
          Tritonbench Scribe Graph Access Token
    inputs:
      job_name:
        required: True
        type: string
        description: |
          Job Name
      conda_env:
        required: True
        type: string
        description: |
          Conda environment to activate when testing Triton

jobs:
  linux-test-h100:
    if: github.repository_owner == 'pytorch-labs'
    runs-on: [gcp-h100-runner]
    timeout-minutes: 240
    environment: docker-s3-upload
    env:
      SETUP_SCRIPT: "/workspace/setup_instance.sh"
      CONDA_ENV: ${{ inputs.conda_env }}
      JOB_NAME: ${{ inputs.job_name }}
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}
    steps:
      - name: Checkout Tritonbench (if on pull_request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Tune Nvidia GPU
        run: |
          sudo nvidia-smi -pm 1
          sudo ldconfig
          nvidia-smi
      - name: Nightly benchmarking
        run: |
          if [ "${GITHUB_EVENT_NAME}" != "pull_request" ]; then
            cd /workspace/tritonbench
          fi
          bash ./.ci/tritonbench/test-nightly.sh
          cp -r ./.benchmarks/nightly benchmark-output
      - name: Upload result to GH Actions Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.job_name }}
          path: benchmark-output/
      - name: Upload result to Scribe
        run: |
          if [ "${GITHUB_EVENT_NAME}" != "pull_request" ]; then
            cd /workspace/tritonbench
          fi
          latest_result_json=$(find ./benchmark-output/ -name "result.json"  | sort -r | head -n 1)
          bash ./.ci/scribe/upload.py --json ${latest_result_json}
