name: linux-test-h100
on:
  workflow_call:
    inputs:
      conda_env:
        required: True
        type: string
        description: |
          Conda environment to activate when testing Triton

jobs:
  linux-test-h100:
    if: github.repository_owner == 'pytorch-labs'
    runs-on: [gcp-h100-runner]
    timeout-minutes: 240
    environment: docker-s3-upload
    env:
      SETUP_SCRIPT: "/workspace/setup_instance.sh"
      CONDA_ENV: ${{ inputs.conda_env }}
    steps:
      - name: Checkout Tritonbench
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Tune Nvidia GPU
        run: |
          sudo nvidia-smi -pm 1
          sudo ldconfig
          nvidia-smi
      - name: Install Tritonbench
        run: |
          # todo: remove this when the new docker rolls out
          mkdir -p /workspace/tritonbench/.data
          # speedup install and skip compile
          ln -s /workspace/tritonbench/.data .
          . "${SETUP_SCRIPT}"
          python install.py --colfax --tk --hstu
      - name: Test Tritonbench operators on H100 GPU
        run: |
          bash ./.ci/tritonbench/test-gpu.sh
