name: Triton Compile Time Benchmark
on:
  schedule:
    # Run nightly at 4 PM UTC after the nightly docker is updated
    - cron: '0 16 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - benchmarks/compile_time/**
      - .github/workflows/_linux-benchmark-h100.yml
      - .github/workflows/compile-time.yml

jobs:
  h100-triton-main-compile-time-benchmark:
    uses: ./.github/workflows/_linux-benchmark-h100.yml
    with:
      conda_env: "triton-main"
      benchmark_name: "compile_time"
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}



concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
