name: TritonBench PR Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  h100-pytorch-test:
    uses: ./.github/workflows/_linux-test-h100.yml
    with:
      conda_env: "pytorch"
  h100-triton-main-test:
    uses: ./.github/workflows/_linux-test-h100.yml
    with:
      conda_env: "triton-main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
